var myName = document.getElementById("name");
var desig = document.getElementById("desig");
var Phone = document.getElementById("Phone");
var email = document.getElementById("email");
var add = document.getElementById("add");
var LinkedIn = document.getElementById("LinkedIn");
var pic = document.getElementById("pic");
var pass = document.getElementById("pass");
var deg = document.getElementById("deg");
var uni = document.getElementById("uni");
var pass2 = document.getElementById("pass2");
var deg2 = document.getElementById("deg2");
var uni2 = document.getElementById("uni2");
var skill1 = document.getElementById("skill1");
var skill_level1 = document.getElementById("skill_level1");
var skill2 = document.getElementById("skill2");
var skill_level2 = document.getElementById("skill_level2");
var skill3 = document.getElementById("skill3");
var skill_level3 = document.getElementById("skill_level3");
var skill4 = document.getElementById("skill4");
var skill_level4 = document.getElementById("skill_level4");
var lang = document.getElementById("lang");
var lang2 = document.getElementById("lang2");
var styear = document.getElementById("styear");
var endyear = document.getElementById("endyear");
var company = document.getElementById("company");
var comlocation = document.getElementById("comlocation");
var jobTitle = document.getElementById("jobTitle");
var achv1 = document.getElementById("achv1");
var achv2 = document.getElementById("achv2");
var achv3 = document.getElementById("achv3");
var styear2 = document.getElementById("styear2");
var endyear2 = document.getElementById("endyear2");
var company2 = document.getElementById("company2");
var comlocation2 = document.getElementById("comlocation2");
var jobTitle2 = document.getElementById("jobTitle2");
var achv12 = document.getElementById("achv12");
var achv22 = document.getElementById("achv22");
var achv32 = document.getElementById("achv32");
//----------------   Education Add More -------------------------------------------------
var addEdu = document.getElementById("addEdu");
var eduDetails2 = document.getElementById("eduDetails2");
addEdu === null || addEdu === void 0 ? void 0 : addEdu.addEventListener('click', function () {
    eduDetails2 === null || eduDetails2 === void 0 ? void 0 : eduDetails2.classList.remove('hideUnhide');
});
//----------------   skill Add More -------------------------------------------------
var addSkill = document.getElementById("addSkill");
var expertiseDetails2 = document.getElementById("expertiseDetails2");
addSkill === null || addSkill === void 0 ? void 0 : addSkill.addEventListener('click', function () {
    expertiseDetails2 === null || expertiseDetails2 === void 0 ? void 0 : expertiseDetails2.classList.remove('hideUnhide');
});
//----------------   skill Add More -------------------------------------------------
var addExp = document.getElementById("addExp");
var expDetails2 = document.getElementById("expDetails2");
addExp === null || addExp === void 0 ? void 0 : addExp.addEventListener('click', function () {
    expDetails2 === null || expDetails2 === void 0 ? void 0 : expDetails2.classList.remove('hideUnhide');
});
//----------------   form submit -------------------------------------------------
var form = document.getElementById('form');
form === null || form === void 0 ? void 0 : form.addEventListener('submit', function (e) {
    e.preventDefault();
    localStorage.setItem('myName', myName.value);
    console.log(localStorage.getItem('myName'));
    localStorage.setItem('desig', desig.value);
    console.log(localStorage.getItem('desig'));
    localStorage.setItem('Phone', Phone.value);
    console.log(localStorage.getItem('Phone'));
    localStorage.setItem('email', email.value);
    console.log(localStorage.getItem('email'));
    localStorage.setItem('add', add.value);
    console.log(localStorage.getItem('add'));
    localStorage.setItem('LinkedIn', LinkedIn.value);
    console.log(localStorage.getItem('LinkedIn'));
    localStorage.setItem('pic', pic.value);
    console.log(localStorage.getItem('pic'));
    localStorage.setItem('pass', pass.value);
    console.log(localStorage.getItem('pass'));
    localStorage.setItem('deg', deg.value);
    console.log(localStorage.getItem('deg'));
    localStorage.setItem('uni', uni.value);
    console.log(localStorage.getItem('uni'));
    localStorage.setItem('pass2', pass2.value);
    console.log(localStorage.getItem('pass2'));
    localStorage.setItem('deg2', deg2.value);
    console.log(localStorage.getItem('deg2'));
    localStorage.setItem('uni2', uni2.value);
    console.log(localStorage.getItem('uni2'));
    localStorage.setItem('skill1', skill1.value);
    console.log(localStorage.getItem('skill1'));
    localStorage.setItem('skill_level1', skill_level1.value);
    console.log(localStorage.getItem('skill_level1'));
    localStorage.setItem('skill2', skill2.value);
    console.log(localStorage.getItem('skill2'));
    localStorage.setItem('skill_level2', skill_level2.value);
    console.log(localStorage.getItem('skill_level2'));
    localStorage.setItem('skill3', skill3.value);
    console.log(localStorage.getItem('skill3'));
    localStorage.setItem('skill_level3', skill_level3.value);
    console.log(localStorage.getItem('skill_level3'));
    localStorage.setItem('skill4', skill4.value);
    console.log(localStorage.getItem('skill4'));
    localStorage.setItem('skill_level4', skill_level4.value);
    console.log(localStorage.getItem('skill_level4'));
    localStorage.setItem('lang', lang.value);
    console.log(localStorage.getItem('lang'));
    localStorage.setItem('lang2', lang2.value);
    console.log(localStorage.getItem('lang2'));
    localStorage.setItem('styear', styear.value);
    console.log(localStorage.getItem('styear'));
    localStorage.setItem('endyear', endyear.value);
    console.log(localStorage.getItem('endyear'));
    localStorage.setItem('company', company.value);
    console.log(localStorage.getItem('company'));
    localStorage.setItem('comlocation', comlocation.value);
    console.log(localStorage.getItem('comlocation'));
    localStorage.setItem('jobTitle', jobTitle.value);
    console.log(localStorage.getItem('jobTitle'));
    localStorage.setItem('achv1', achv1.value);
    console.log(localStorage.getItem('achv1'));
    localStorage.setItem('achv2', achv2.value);
    console.log(localStorage.getItem('achv2'));
    localStorage.setItem('achv3', achv3.value);
    console.log(localStorage.getItem('achv3'));
    localStorage.setItem('styear2', styear2.value);
    console.log(localStorage.getItem('styear2'));
    localStorage.setItem('endyear2', endyear2.value);
    console.log(localStorage.getItem('endyear2'));
    localStorage.setItem('company2', company2.value);
    console.log(localStorage.getItem('company2'));
    localStorage.setItem('comlocation2', comlocation2.value);
    console.log(localStorage.getItem('comlocation2'));
    localStorage.setItem('jobTitle2', jobTitle2.value);
    console.log(localStorage.getItem('jobTitle2'));
    localStorage.setItem('achv12', achv12.value);
    console.log(localStorage.getItem('achv12'));
    localStorage.setItem('achv22', achv22.value);
    console.log(localStorage.getItem('achv22'));
    localStorage.setItem('achv32', achv32.value);
    console.log(localStorage.getItem('achv32'));
    if (pic.files && pic.files[0]) {
        var reader_1 = new FileReader();
        reader_1.onload = function () {
            var base64Image = reader_1.result;
            localStorage.setItem('form_profilePic', base64Image);
            console.log(localStorage.getItem('form_profilePic'));
            window.location.href = "../simple_layout/simpleLayout.html";
        };
        reader_1.readAsDataURL(pic.files[0]);
    }
    else {
        window.location.href = "../simple_layout/simpleLayout.html";
    }
});
